from .state import AgentState
from backend.tools.system import SystemCommandTool
from backend.tools.browser import BrowserTool
from backend.tools.monitor import SystemMonitorTool
from backend.tools.filesystem import FileSystemTools
from backend.tools.vision import VisionTool
from backend.tools.desktop import DesktopTool
from backend.security.audit import audit_logger
from backend.plugins.plugin_manager import plugin_manager
import re
import asyncio
import json

# Instantiate tools
system_tool = SystemCommandTool(use_sandbox=False) 
browser_tool = BrowserTool()
monitor_tool = SystemMonitorTool()
fs_tool = FileSystemTools()
vision_tool = VisionTool()
desktop_tool = DesktopTool()

# Tools are loaded dynamically per-execution from plugin_manager


def executor_node(state: AgentState):
    """
    Executes the next step in the plan using available tools.
    """
    if not state.get("plan"):
        return {"final_response": "No plan was generated by the System Agent.", "tool_calls": []}
        
    step_idx = state.get("current_step_idx", 0)
    if step_idx >= len(state.get("plan", [])):
        return {"tool_calls": []}
        
    current_step = state["plan"][step_idx]
    
    # Check if we just came back from approval
    approval_status = state.get("approval_status", "none")
    tool_calls = state.get("tool_calls", [])
    
    if approval_status == "approved" and tool_calls:
        # Actually execute the tool
        call = tool_calls[0]
        action = call.get("action")
        args = call.get("args", {})
        
        # Always get the latest hot-reloaded plugin map
        plugin_tools_map = plugin_manager.get_all_tools()
        
        audit_logger.log_event("TOOL_EXECUTION", "INFO", {
            "action": action,
            "args": args,
            "status": "started"
        })
        
        result = "Tool execution failed."
        try:
            if action == "system_command":
                result = system_tool.execute(args.get("command", ""))
            elif action == "browser_goto":
                try:
                    loop = asyncio.get_event_loop()
                    result = loop.run_until_complete(browser_tool.navigate_and_extract(args.get("url", "")))
                except RuntimeError:
                    result = asyncio.run(browser_tool.navigate_and_extract(args.get("url", "")))
            elif action == "read_file":
                result = fs_tool.read_file(args.get("filepath", ""))
            elif action == "write_file":
                result = fs_tool.write_file(args.get("filepath", ""), args.get("content", ""))
            elif action == "list_dir":
                result = fs_tool.list_dir(args.get("directory", ""))
            elif action == "system_monitor":
                result = monitor_tool.get_system_metrics()
            elif action == "desktop_type":
                result = desktop_tool.type_text(args.get("text", ""))
            elif action == "analyze_screen":
                result = vision_tool.analyze_screen(args.get("question", "What is on my screen?"))
            elif action == "respond_to_user":
                result = args.get("text", "")
            elif action in plugin_tools_map:
                # Dynamically execute mapped plugin
                try:
                    target_func = plugin_tools_map[action]["callable"]
                    result = target_func(**args)
                except Exception as plugin_err:
                    result = f"Error: Custom plugin '{action}' managed to crash during execution: {str(plugin_err)}. Please inform the user."
            else:
                result = f"Error: Unknown tool '{action}'"

            audit_logger.log_event("TOOL_EXECUTION", "SUCCESS", {
                "action": action,
                "result_preview": str(result)[:200]
            })
        except Exception as e:
            result = f"Error: {str(e)}"
            audit_logger.log_event("TOOL_EXECUTION", "ERROR", {
                "action": action,
                "error": str(e)
            })
            
        # We would log this result to memory in a real implementation
        
        # Reset approval and move to next step
        return {
            "tool_calls": [], 
            "approval_status": "none",
            "current_step_idx": step_idx + 1,
            "final_response": result if action == "respond_to_user" else ""
        }
    elif approval_status == "rejected":
        # Handled by graph conditional edge usually, but safe to clear here
        return {"tool_calls": [], "approval_status": "none", "final_response": "Task aborted by user."}
    
    
    # Basic scaffolding Logic: map text directives to tools
    tool_call = {
        "action": "system_command", 
        "args": {"command": f"echo 'Invalid ReAct format or missing Action/Action Input tags'"}
    }
    
    try:
        if "Action:" in current_step and "Action Input:" in current_step:
            action_part = current_step.split("Action:")[1].split("Action Input:")[0].strip()
            input_part = current_step.split("Action Input:")[1].strip()
            
            # Extract JSON block if it's wrapped in markers
            json_str = input_part
            match = re.search(r'```(?:json)?\n?(.*?)\n?```', input_part, re.DOTALL)
            if match:
                json_str = match.group(1).strip()
                
            args = json.loads(json_str)
            tool_call = {
                "action": action_part,
                "args": args
            }
    except Exception as e:
        tool_call["args"]["command"] = f"echo 'Parse error: {e}'"
        
    # Determine Risk Level
    risk_level = "medium"
    high_risk = ["system_command", "write_file"]
    low_risk = ["read_file", "list_dir", "system_monitor"]
    
    # Always get the latest hot-reloaded plugin map to determine risk level
    plugin_tools_map = plugin_manager.get_all_tools()
    
    if tool_call["action"] in high_risk:
        risk_level = "high"
    elif tool_call["action"] in low_risk:
        risk_level = "low"
    elif tool_call["action"] in plugin_tools_map:
        # Default all custom plugins to medium risk for scaffolding
        risk_level = "medium"
        
    tool_call["riskLevel"] = risk_level
    
    # Check for autonomous mode auto-approval
    is_autonomous = state.get("is_autonomous", False)
    computed_status = "pending"
    if is_autonomous and risk_level in ["low", "medium"]:
        computed_status = "approved"
        
    return {
        "tool_calls": [tool_call], 
        "approval_status": computed_status,
        # Do not advance pointer yet unless auto-approved, wait for approval
    }
