from typing import TypedDict, Annotated, List, Dict, Any, Optional
from langchain_core.messages import BaseMessage
import operator

class AgentState(TypedDict):
    """
    State of the LangGraph multi-agent execution.
    """
    # Using `operator.add` to append messages to the list
    messages: Annotated[List[BaseMessage], operator.add]
    
    # High-level plan generated by Planner
    plan: List[str]
    
    # State tracking
    current_step_idx: int
    error_count: int
    
    # Tool execution status
    tool_calls: List[Dict[str, Any]]
    approval_status: str # "pending", "approved", "rejected", "auto_approved"
    
    # RAG/Memory context
    memory_context: str
    
    # Multi-Agent Routing
    next_agent: str
    is_safe: bool
    is_autonomous: bool
    
    # Final response to be returned to voice/UI
    final_response: str

